apiVersion: apps/v1
kind: Deployment
metadata:
  name: ebr-guess-game-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ebr-guess-game-frontend
  template:
    metadata:
      labels:
        app: ebr-guess-game-frontend
    spec:
      containers:
        - name: frontend
          image: ealen/echo-server
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_BACKEND_URL
              value: "http://guess-backend.aretrix.com"  
---              
apiVersion: v1
kind: Service
metadata:
  name: ebr-guess-game-frontend
spec:
  selector:
    app: ebr-guess-game-frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
